name: Publish to Confluence
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      

      - name: debug
        run: |
          ls -lrt
          pwd

    #   - uses: cupcakearmy/confluence-markdown-sync@v1
    #     with:
    #       from: './README.md'
    #       to: '491521' # The confluence page id where to write the output
    #       cloud: <my-confluence-cloud-id>
    #       user: <my.user@example.org>
    #       token: <my-token>
                
        