name: Publish README to Confluence

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - uses: ./
        with:
          from: './README.md'
          to: '491521' # The confluence page id where to write the output
          cloud: 'vaishnav-vsri'
          user: 'vaishnavsri2@gmail.com'
          token: ${{ secrets.CONFLUENCE_API_TOKEN }}


